In [32]:
import pandas as pd
import json

In [76]:
def get_fd_id(symbol):
    fundamental_id = {'EARNINGS' : 'quarterlyEarnings', 'INCOME_STATEMENT':'quarterlyReports','BALANCE_SHEET':'quarterlyReports',
                  'CASH_FLOW':'quarterlyReports'}
    stock_funda_id = []
    for id, attr in fundamental_id.items():
        print(id, attr)
        url = 'https://www.alphavantage.co/query?function='+ id+'&'+'symbol='+symbol+'&apikey=H40LS6V3016EZSQ6'
        r = requests.get(url)
        data = r.json()
        stock_funda_id.append(pd.DataFrame(data[attr]))
    return  pd.concat(stock_funda_id)

In [85]:
import requests
stocks = ['FUBO','SE']
stock_funda = {}
for symbol in stocks:
     print(symbol)
     stock_funda[symbol] = get_fd_id(symbol)

FUBO
EARNINGS quarterlyEarnings
INCOME_STATEMENT quarterlyReports
BALANCE_SHEET quarterlyReports
CASH_FLOW quarterlyReports
SE
EARNINGS quarterlyEarnings
INCOME_STATEMENT quarterlyReports
BALANCE_SHEET quarterlyReports
CASH_FLOW quarterlyReports

In [88]:
stock_funda['SE']

,fiscalDateEnding,reportedDate,reportedEPS,estimatedEPS,surprise,surprisePercentage,reportedCurrency,grossProfit,totalRevenue,costOfRevenue,...,dividendPayout,dividendPayoutCommonStock,dividendPayoutPreferredStock,proceedsFromIssuanceOfCommonStock,proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet,proceedsFromIssuanceOfPreferredStock,proceedsFromRepurchaseOfEquity,proceedsFromSaleOfTreasuryStock,changeInCashAndCashEquivalents,changeInExchangeRate
0,2021-03-31,2021-05-18,-0.62,-0.5741,-0.0459,-7.9951,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-12-31,2021-03-02,-0.87,-0.7508,-0.1192,-15.8764,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-09-30,2020-11-17,-0.69,-0.552,-0.138,-25,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-06-30,2020-08-18,-0.68,-0.4349,-0.2451,-56.3578,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-03-31,2020-05-18,-0.52,-0.2906,-0.2294,-78.9401,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,2017-06-30,NaN,NaN,NaN,NaN,NaN,USD,NaN,NaN,NaN,...,None,None,None,None,None,None,23000,None,None,None
16,2017-03-31,NaN,NaN,NaN,NaN,NaN,USD,NaN,NaN,NaN,...,None,None,None,None,None,None,1953000,None,None,None
17,2016-12-31,NaN,NaN,NaN,NaN,NaN,USD,NaN,NaN,NaN,...,None,None,None,None,None,None,3210000,None,None,None
18,2016-09-30,NaN,NaN,NaN,NaN,NaN,USD,NaN,NaN,NaN,...,None,None,None,None,None,None,1953000,None,None,None
19,2015-12-31,NaN,NaN,NaN,NaN,NaN,USD,NaN,NaN,NaN,...,None,None,None,None,None,None,185044000,None,None,None

In [84]:
stock_funda['FUBO']['reportedEPS']

0     -0.6703
1     -2.2911
2       -1.65
3      -2.827
4     -0.1474
       ...
15        NaN
16        NaN
17        NaN
18        NaN
19        NaN
Name: reportedEPS, Length: 91, dtype: object

In [79]:
for col_name in stock_funda['FUBO'].columns: 
    print(col_name)

fiscalDateEnding
reportedDate
reportedEPS
estimatedEPS
surprise
surprisePercentage
reportedCurrency
grossProfit
totalRevenue
costOfRevenue
costofGoodsAndServicesSold
operatingIncome
sellingGeneralAndAdministrative
researchAndDevelopment
operatingExpenses
investmentIncomeNet
netInterestIncome
interestIncome
interestExpense
nonInterestIncome
otherNonOperatingIncome
depreciation
depreciationAndAmortization
incomeBeforeTax
incomeTaxExpense
interestAndDebtExpense
netIncomeFromContinuingOperations
comprehensiveIncomeNetOfTax
ebit
ebitda
netIncome
totalAssets
totalCurrentAssets
cashAndCashEquivalentsAtCarryingValue
cashAndShortTermInvestments
inventory
currentNetReceivables
totalNonCurrentAssets
propertyPlantEquipment
accumulatedDepreciationAmortizationPPE
intangibleAssets
intangibleAssetsExcludingGoodwill
goodwill
investments
longTermInvestments
shortTermInvestments
otherCurrentAssets
otherNonCurrrentAssets
totalLiabilities
totalCurrentLiabilities
currentAccountsPayable
deferredRevenue
currentDebt
shortTermDebt
totalNonCurrentLiabilities
capitalLeaseObligations
longTermDebt
currentLongTermDebt
longTermDebtNoncurrent
shortLongTermDebtTotal
otherCurrentLiabilities
otherNonCurrentLiabilities
totalShareholderEquity
treasuryStock
retainedEarnings
commonStock
commonStockSharesOutstanding
operatingCashflow
paymentsForOperatingActivities
proceedsFromOperatingActivities
changeInOperatingLiabilities
changeInOperatingAssets
depreciationDepletionAndAmortization
capitalExpenditures
changeInReceivables
changeInInventory
profitLoss
cashflowFromInvestment
cashflowFromFinancing
proceedsFromRepaymentsOfShortTermDebt
paymentsForRepurchaseOfCommonStock
paymentsForRepurchaseOfEquity
paymentsForRepurchaseOfPreferredStock
dividendPayout
dividendPayoutCommonStock
dividendPayoutPreferredStock
proceedsFromIssuanceOfCommonStock
proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet
proceedsFromIssuanceOfPreferredStock
proceedsFromRepurchaseOfEquity
proceedsFromSaleOfTreasuryStock
changeInCashAndCashEquivalents
changeInExchangeRate

In [ ]:
df[['star_name', 'ra']]